-- Water Cup 💧 (Supabase SQL)
-- Run in Supabase SQL Editor (in order).

-- Extensions
create extension if not exists pgcrypto;

-- Group code generator (simple + fun)
create or replace function public.generate_group_code()
returns text
language sql
as $$
  select upper(substring(encode(gen_random_bytes(4), 'hex') from 1 for 6));
$$;

-- Tables
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text not null unique default public.generate_group_code(),
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  user_id uuid not null references public.users(id) on delete cascade,
  group_id uuid not null references public.groups(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, group_id)
);

create table if not exists public.water_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  group_id uuid not null references public.groups(id) on delete cascade,
  ml integer not null check (ml > 0),
  created_at timestamptz not null default now()
);

-- Indexes (MVP performance)
create index if not exists water_logs_group_created_at_idx on public.water_logs (group_id, created_at desc);
create index if not exists water_logs_user_created_at_idx on public.water_logs (user_id, created_at desc);
create index if not exists group_members_group_idx on public.group_members (group_id);

-- Trigger: auto-create profile row on auth user create
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', 'Sem nome'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- Week window (Monday -> Sunday) is handled in SQL via date_trunc('week', now()).
-- In Postgres, date_trunc('week', ...) follows ISO weeks (Monday start).

create or replace view public.weekly_leaderboard as
with week_logs as (
  select *
  from public.water_logs wl
  where wl.created_at >= date_trunc('week', now())
    and wl.created_at < (date_trunc('week', now()) + interval '7 days')
)
select
  wl.group_id,
  wl.user_id,
  u.name,
  sum(wl.ml)::bigint as total_ml,
  (sum(wl.ml)::numeric / 1000.0) as total_liters
from week_logs wl
join public.users u on u.id = wl.user_id
group by wl.group_id, wl.user_id, u.name;

-- Default "fixed" group (MVP): create if none exists
do $$
begin
  if not exists (select 1 from public.groups) then
    insert into public.groups (name) values ('Rapaziada Dev');
  end if;
end;
$$;

-- Realtime publication (required for postgres_changes)
-- If you get "publication does not exist", run this in Supabase:
--   alter publication supabase_realtime add table public.water_logs;
-- On newer projects, the publication exists by default:
do $$
begin
  -- Add table to publication only if not already present
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'water_logs'
  ) then
    alter publication supabase_realtime add table public.water_logs;
  end if;
end;
$$;

-- RLS
alter table public.users enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.water_logs enable row level security;

-- Policies: simple MVP, authenticated-only
drop policy if exists "users_select_auth" on public.users;
create policy "users_select_auth"
on public.users for select
to authenticated
using (true);

drop policy if exists "users_upsert_own" on public.users;
create policy "users_upsert_own"
on public.users for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "users_update_own" on public.users;
create policy "users_update_own"
on public.users for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "groups_select_auth" on public.groups;
create policy "groups_select_auth"
on public.groups for select
to authenticated
using (true);

drop policy if exists "groups_insert_auth" on public.groups;
create policy "groups_insert_auth"
on public.groups for insert
to authenticated
with check (true);

drop policy if exists "members_select_same_groups" on public.group_members;
create policy "members_select_same_groups"
on public.group_members for select
to authenticated
using (
  group_id in (select gm.group_id from public.group_members gm where gm.user_id = auth.uid())
);

drop policy if exists "members_insert_self" on public.group_members;
create policy "members_insert_self"
on public.group_members for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "members_delete_self" on public.group_members;
create policy "members_delete_self"
on public.group_members for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "water_select_member" on public.water_logs;
create policy "water_select_member"
on public.water_logs for select
to authenticated
using (
  group_id in (select gm.group_id from public.group_members gm where gm.user_id = auth.uid())
);

drop policy if exists "water_insert_member" on public.water_logs;
create policy "water_insert_member"
on public.water_logs for insert
to authenticated
with check (
  user_id = auth.uid()
  and group_id in (select gm.group_id from public.group_members gm where gm.user_id = auth.uid())
);

-- Optional: allow deleting own logs (not used in UI, but handy)
drop policy if exists "water_delete_own" on public.water_logs;
create policy "water_delete_own"
on public.water_logs for delete
to authenticated
using (user_id = auth.uid());

